version: "3.8"

services:

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats_service_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=main_service_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  stats-server:
    build: stats/service
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db/stats_service_db


  ewm-service:
    build: service
    container_name: main-service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db/main_service_db
      - SPRING_STATS-SERVICE_URI=http://stats-server:9090


